version: "3.9"
services:
    app:
        build: .
        image: ${DOCKER_USER_ID}/flask
    production:
        image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
        command: python app.py
        volumes:
            - .:/code
        ports:
            - "9001:9001"