version: '3'
services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ../app:/home/app
        ports:
            - "9001:9001"
        
    